/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.alessio.assemblatore.resources;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 * @author aless
 */
@DynamoDBTable(tableName = "RamTableTest")
public class RamMapper {
    private String idRam;
    private double price;
    private String brandRam;
    private int size;
    private String uuid;
    
    
    @DynamoDBHashKey(attributeName = "Uuid")
    @DynamoDBAutoGeneratedKey
    public String getUuid() {return uuid;}
    public void setUuid(String uuid) {this.uuid = uuid;}
    
    @DynamoDBAttribute(attributeName = "IdRam")
    public String getIdRam() {return idRam;}
    public void setIdRam(String idRam) {this.idRam = idRam;}

    @DynamoDBAttribute(attributeName = "Price")
    public double getPrice() {return price;}
    public void setPrice(double price) {this.price = price;}

    @DynamoDBAttribute(attributeName = "BrandRam")
    public String getBrandRam() {return brandRam;}
    public void setBrandRam(String brandRam) {this.brandRam = brandRam;}

    @DynamoDBAttribute(attributeName = "Size")
    public int getSize() {return size;}
    public void setSize(int size) {this.size = size;}
}
